name: Tailwindcss build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Update
        run: sudo apt update
      - name: Install node
        run: sudo apt install nodejs
      - name: Install npm
        run: sudo apt install npm
      - name: Install tailwindcss
        run: npm install -D tailwindcss
      - name: Build tailwind app
        working-directory: ./
        run: npx tailwindcss -i ./src/in.css -o ./src/style.css
      - name: Commit
        run: |
          git config --global user.name 'Givinghawk'
          git config --global user.email 'givinghawk@users.noreply.github.com'
          git commit -am "Tailwind build (AUTOMATED)"
          git push
