# This is a basic workflow to help you get started with Actions

name: Tailwindcss build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Update
        run: sudo apt update
      - name: Install node
        run: sudo apt install nodejs
      - name: Install npm
        run: sudo apt install npm
      - name: Install tailwindcss
        run: npm install -D tailwindcss
      - name: Build tailwind app
        working-directory: ./
        run: npx tailwindcss -i ./src/in.css -o ./src/style.css
      - name: Commit report
        run: |
          git config --global user.name 'Givinghawk'
          git config --global user.email 'givinghawk@users.noreply.github.com'
          git commit -am "Tailwind build (AUTOMATED)"
          git push
